ESSID='wifi network id'
WIFI_PASSWORD='wifi password'
VAN_ID='your van id - you get this when you register a vehicle on the website'
USER_ID='your user id...  you get this when you register a vehicle on the website'
API_URL='https://whatevs.com'
